# Copyright (C) 2021 Stephan Wendel <me@stephanwe.de>
#
# This file may be distributed under the terms of the GNU GPLv3 license

version: "3.9"
services:
  mainsaildocs:
    image: jekyll/jekyll:latest
    environment:
      - JEKYLL_ENV=docker
    #stdin_open: true
    tty: true
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - ./docs:/srv/jekyll
      - ./_config.docker.yml:/docker/_config.docker.yml
    command: |
      jekyll serve
      --config _config.yml,/docker/_config.docker.yml
      --incremental
      --livereload
      --livereload-min-delay 1
      --livereload-max-delay 3
      --force_polling
